import Head from 'next/head'
import Image from 'next/image'
import InitialScreen from '../components/initialScreen'
import NavigationTwo from '../components/NavTwo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Surto - Marketing Inteligente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InitialScreen />
      <main>
        <NavigationTwo />
      </main>
    </>
  )
}
